# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170511_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Categories de jean-kevin',
            },
        ),
    ]
